### ISSUE TITLE
Add DB host and port to mongo DB connection string

### ISSUE THREAD

**Issue by Aymane11** [yezz123/fastapi-lazy#14]
In the [mongo.py file](https://github.com/yezz123/fastapi-lazy/blob/main/fastapi_lazy/database/mongo.py#L5) the link uses `mongo` as host and `27017` as a port, in some cases, user might want to use a different host and port, so these fields should be modifiable ? Maybe use `os.environ.get('MONOGO_HOST','some-default-value')` ?

**Comment by yezz123** [comment]
Yes, This is a good thing, I forget to change most of the default ones, I will add the default one & Modifiable one 👌🏻.
Thanks @Aymane11 🚀
